PREFIX ex: <http://www.w3.org/2009/sparql/docs/tests/data-it.polimi.jasper.engine.querying.syntax.sparql11/negation#>
SELECT ?animal { 
  ?animal a ex:Animal MINUS { 
    ?animal a ?type 
    FILTER(?type = ex:Reptile || ?type = ex:Insect) 
  } 
}